### ISSUE TITLE
Unsupported class version error

### ISSUE THREAD

**Issue by dicleoztur** [dkpro/dkpro-statistics#23]
hi,
i have dkpro-statistics with version 2.0.1 in our pom file. when i import the library and use the related classes, i receive'the following error and couldn't find a work around: "Exception in thread "main" java.lang.UnsupportedClassVersionError: org/dkpro/statistics/agreement/distance/IDistanceFunction : Unsupported major.minor version 52.0"
i use java1.7.

**Comment by chmeyer** [comment]
The latest version requires Java 8. Solutions: 
- update your JDK
- checkout the trunk and downgrade the parent POM + replace Java-8-specific code snippets (shouldn't be many so far)
- use an older release (not recommended)
